name: lighthouse

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install lighthouse
        run: sudo npm i -g lighthouse
      - name: RUN lighthouse
        run: |
          lighthouse \
            --output html --output-path ./report.html
      - name: upload result
        uses: actions/upload-artifact@master
        with:
          name: report
          path: report.html
