name: lighthouse

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

jobs:
  build:
    runs_on: ubuntu-latest

    strategy:
    matrix:
      node-version:[10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install lighthouse
      uses: sudo npm i -g lighthouse
      name: RUN lighthouse
      run: |
        npm install -g @lhci/cli@0.3.x
        lighthouse \
          -- chrome-flags-"--headless"\
          --output html --output-path ./report.html
      name: upload result
      uses: actions/upload-artifact@master
      with: 
        name: report
        path: report.html